#! /bin/bash

set -eu -o pipefail

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
	CREATE USER ${POSTGRES_SUBUSER} WITH ENCRYPTED PASSWORD '${POSTGRES_SUBUSER_PASSWORD}';
	CREATE DATABASE ${POSTGRES_SUBDB} OWNER ${POSTGRES_SUBUSER};
	GRANT ALL PRIVILEGES ON DATABASE ${POSTGRES_SUBDB} TO ${POSTGRES_SUBUSER};
EOSQL

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_SUBUSER" --dbname "$POSTGRES_SUBDB" <<-EOSQL
  ALTER SCHEMA public OWNER TO ${POSTGRES_SUBUSER}
EOSQL
