import {DepGraph} from './dependency-graph';

export const KMID = {
  // You can add constants here, but exiting ones MUST NEVER BE CHANGED.
  // They are used to keep the state of the knowledge map in sync, potentially
  // across versions. So they must not change since that may break compatibility
  // when something is upgraded.
  EN_REPEAT_VOWEL_SOUNDS: '',
  EN_REPEAT_CONSONANT_SOUNDS: '',
  EN_REPEAT_SOUNDS: '',
  EN_RECOGNIZE_SIMPLE_OBJECTS: '',
  EN_SPEAK_SIMPLE_OBJECTS: '',
  EN_REPEAT_VOWELS: '',
  EN_REPEAT_CONSONANTS: '',
  EN_REPEAT_LETTERS: '',
  EN_SPEAK_ALPHABET: '',
  EN_SPEAK_LOWERCASE_VOWELS: '',
  EN_SPEAK_LOWERCASE_CONSONANTS: '',
  EN_SPEAK_LOWERCASE_LETTERS: '',
  EN_SPEAK_UPPERCASE_VOWELS: '',
  EN_SPEAK_UPPERCASE_CONSONANTS: '',
  EN_SPEAK_UPPERCASE_LETTERS: '',
  EN_SPEAK_LETTERS: '',
};
for (let k in KMID) {
  KMID[k as keyof typeof KMID] = k;
}


let graph = new DepGraph();

graph.addNodeX(KMID.EN_REPEAT_VOWEL_SOUNDS);

graph.addNodeX(KMID.EN_REPEAT_CONSONANT_SOUNDS);

graph.addNodeX(KMID.EN_REPEAT_SOUNDS, [
  KMID.EN_REPEAT_VOWEL_SOUNDS,
  KMID.EN_REPEAT_CONSONANT_SOUNDS,
]);

graph.addNodeX(KMID.EN_RECOGNIZE_SIMPLE_OBJECTS);

graph.addNodeX(KMID.EN_SPEAK_SIMPLE_OBJECTS, [
  KMID.EN_REPEAT_SOUNDS,
  KMID.EN_RECOGNIZE_SIMPLE_OBJECTS,
]);

graph.addNodeX(KMID.EN_REPEAT_VOWELS, [
  KMID.EN_REPEAT_VOWEL_SOUNDS,
]);

graph.addNodeX(KMID.EN_REPEAT_CONSONANTS, [
  KMID.EN_REPEAT_CONSONANT_SOUNDS,
]);

graph.addNodeX(KMID.EN_REPEAT_LETTERS, [
  KMID.EN_REPEAT_VOWELS, KMID.EN_REPEAT_CONSONANTS,
]);

graph.addNodeX(KMID.EN_SPEAK_ALPHABET, [
  KMID.EN_REPEAT_LETTERS,
]);

graph.addNodeX(KMID.EN_SPEAK_LOWERCASE_VOWELS, [
  KMID.EN_REPEAT_VOWELS,
]);

graph.addNodeX(KMID.EN_SPEAK_LOWERCASE_CONSONANTS, [
  KMID.EN_REPEAT_CONSONANTS,
]);

graph.addNodeX(KMID.EN_SPEAK_LOWERCASE_LETTERS, [
  KMID.EN_SPEAK_LOWERCASE_VOWELS, KMID.EN_SPEAK_LOWERCASE_CONSONANTS,
]);

graph.addNodeX(KMID.EN_SPEAK_UPPERCASE_VOWELS, [
  KMID.EN_REPEAT_VOWELS,
]);

graph.addNodeX(KMID.EN_SPEAK_UPPERCASE_CONSONANTS, [
  KMID.EN_REPEAT_CONSONANTS,
]);

graph.addNodeX(KMID.EN_SPEAK_UPPERCASE_LETTERS, [
  KMID.EN_SPEAK_UPPERCASE_VOWELS, KMID.EN_SPEAK_UPPERCASE_CONSONANTS,
]);

graph.addNodeX(KMID.EN_SPEAK_LETTERS, [
  KMID.EN_SPEAK_LOWERCASE_LETTERS, KMID.EN_SPEAK_UPPERCASE_LETTERS,
]);

export const KM = graph;
