name: CI - Lint, Build, Test, and E2E

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Navigate to client and install dependencies
        working-directory: images/psapp/client
        run: bun install --frozen-lockfile

      - name: Run ESLint
        working-directory: images/psapp/client
        run: bun run lint

      # Build must run before typecheck because it generates available-modules.json
      - name: Build client
        working-directory: images/psapp/client
        run: bun run build

      - name: Run client TypeScript type checking
        working-directory: images/psapp/client
        run: bun run typecheck

      - name: Run Tests
        working-directory: images/psapp/client
        run: bun test

      - name: Install server dependencies
        working-directory: images/psapp/server
        run: bun install --frozen-lockfile

      - name: Run server TypeScript type checking
        working-directory: images/psapp/server
        run: bun run typecheck

  integration-tests:
    runs-on: ubuntu-latest
    needs: lint-build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build and run integration tests
        run: |
          cd tests/integration
          chmod +x test.sh
          ./test.sh

  e2e-tests:
    runs-on: ubuntu-latest
    needs: lint-build-test

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Generate self-signed certificates
        run: |
          cd images/psingress/certs
          chmod +x generate-certs.sh
          ./generate-certs.sh

      - name: Install certificates to system store
        run: |
          sudo cp images/psingress/certs/presupplied-selfsigned.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates

      - name: Add applocal.presupplied.com to /etc/hosts
        run: |
          echo "127.0.0.1 applocal.presupplied.com" | sudo tee -a /etc/hosts

      - name: Start Presupplied application
        run: |
          chmod +x run.sh
          ./run.sh &
          # Wait for services to be ready
          echo "Waiting for application to start..."
          timeout 180 bash -c 'until curl -k -s https://applocal.presupplied.com/ 2>/dev/null; do sleep 5; done'

      - name: Run E2E tests
        run: |
          cd tests/e2e
          chmod +x test.sh
          ./test.sh

      - name: Stop application containers
        if: always()
        run: |
          docker-compose down || true
