name: Lint, Build, and Test

on:
  push:
    branches: ['**']
  pull_request:
    branches: ['**']

jobs:
  lint-build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Navigate to client and install dependencies
        working-directory: images/psapp/client
        run: bun install --frozen-lockfile

      - name: Run ESLint
        working-directory: images/psapp/client
        run: bun run lint

      - name: Build client
        working-directory: images/psapp/client
        run: bun run build

      - name: Run Tests
        working-directory: images/psapp/client
        run: bun test

      - name: Install server dependencies
        working-directory: images/psapp/server
        run: bun install --frozen-lockfile

      - name: Verify server build
        working-directory: images/psapp/server
        run: bun run verifyBuild
